### PR TITLE
Bring back scrolling

### LINKED ISSUE #323: Scroll command is broken in webkit2
the scroll command is broken in webkit2.

Is there a new api we can use to implement this?
Is it possible to add this functionality with the web-extension?

### PR DESCRIPTION
**Pull request by keis**
Implement scroll command using web extension

Introduces a new extension message EXT_SCROLL that can scroll the
current web view. It makes use of the webkit DOM api bindings and will
either use scroll_by or scroll_to depending on the requested action.

Fixes #323

### CODE REVIEW

File: src/uzbl-ext.c [hunk 1]
```diff
@@ -167,3 +189,60 @@ dom_blur_callback (WebKitDOMEventTarget *target,
...
+            axis == SCROLL_HORIZONTAL ? webkit_dom_element_get_scroll_width (body)
+                                      : webkit_dom_dom_window_get_scroll_x (win),
+            axis == SCROLL_HORIZONTAL ? webkit_dom_dom_window_get_scroll_y (win)
+                                      : webkit_dom_element_get_scroll_height (body)
+        );
+    } else if (action == SCROLL_SET) {
+        if (mode == SCROLL_PERCENTAGE) {
+            glong page = (axis == SCROLL_HORIZONTAL) ? webkit_dom_element_get_scroll_width (body)
+                                                     : webkit_dom_element_get_scroll_height (body);
+            amount = (gint32) page * amount * 0.01;
```
Comment (mathstuf) [inline src/uzbl-ext.c]: My gut is telling me something is wrong with this math. Can't put my finger on it right now though.

Comment (keis) [inline src/uzbl-ext.c]: the old code had a concept lower and upper values that was queried from gtk in dom land nothing like this exist. It might make sense to deduct the view port size here as scrolling to 100% of the page is nonsense request. Scrolling is defined by where the top of the viewport and that would put it entirely outside of the page.

Comment (mathstuf) [inline src/uzbl-ext.c]: Ah, yeah. The viewport size is what is missing then. Otherwise the range is discontinuous and there are some high percentages which are indistinguishable from each other.

**Comment by keis** [comment]
The big scroll function is looking very verbose and repetitive coming back to it but being clever about it is perhaps a later problem

**Comment by mathstuf** [comment]
Hmm. This isn't working here, but for more fundamental reasons. First, the extension isn't installed at all. Second, once I do install it, it isn't being loaded. Investigating.

**Comment by mathstuf** [comment]
Oh, it is being loaded; wasn't tracing child processes. However, I am not able to scroll here. Debugging further.

**Comment by keis** [comment]
hehe. ok. awesome
